import type { Metadata } from "next";
import "./globals.css";
import { lusitana } from "./lib/fonts";
import { Providers } from "./lib/providers";

export const metadata: Metadata = {
  title: "BCA HealthCare",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lusitana.className}`}>
      <Providers>
        {children}
      </Providers>
      </body> 
    </html>
   
  );
}
