import type { Metadata } from "next";
import { Inter, Lusitana } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { Session } from "next-auth";
// import { getServerSession } from "next-auth";



export const lusitana = Lusitana({subsets:["latin"], weight:"400"})

export const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "BCA HealthCare",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, session
}: Readonly<{
  children: React.ReactNode;
  session: Session| null
}>) {
  return (
    <html lang="en">
      <body className={`${lusitana.className}`}>
        {/* <SessionProvider session={session as Session | null}> */}
        <span className="min-h-screen bg-gray-100">{children}</span>
        {/* </SessionProvider> */}
      </body>      
    </html>
  );
}
