import type { Metadata } from "next";
import { Inter, Lusitana } from "next/font/google";
import "./globals.css";
import Footer from "./ui/footer";



const lusitana = Lusitana({subsets:["latin"], weight:"400"})

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "BCA HealthCare",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lusitana.className}`}>
        <span className="min-h-screen bg-gray-100">{children}</span>
      <Footer/>
      </body>      
    </html>
  );
}
