import type { Metadata } from "next";
import { Inter, Lusitana } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });
const lusitana = Lusitana({subsets:["latin"], weight:"400"})

export const metadata: Metadata = {
  title: "BCA HealthCare",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <Provider store={store}>
      <div className={`${lusitana.className}`}>
        <span className="bg-gray-100">{children}</span>
      </div>  
    // </Provider>    
  );
}